name = "field-officer-tracker"
main = "src/index.js"
compatibility_date = "2025-06-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "field-officers"
database_id = "51b96147-1ee3-45a1-8eda-de25378dcb1a"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "field-officer-photos"

[vars]
ORG_NAME = "SKD Health"
CONTACT_EMAIL = "sujith.dn@skdhealth.com"

[observability]
enabled = true
